site_name: Neverfelly's wiki

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

extra_css:
  - 'static/css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - 'static/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'

nav:
  - Preface: 
    - Introduction: index.md
  - MachineLearning :
    - ComputerVision:
      - Basic: ml/cv/basic.md
  - Graphics :
    - Rendering:
      - Basic: graphics/rendering/basic.md
      - Offline: graphics/rendering/offline.md
      - Reflection: graphics/rendering/reflection.md
    - Simulation:
      - Basic: graphics/simulation/basic_def.md
      - SPH: graphics/simulation/sph.md

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
